/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SIMPLE_BUFFER_H
#define _MOCK_SIMPLE_BUFFER_H

#include "simple_buffer.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#pragma GCC diagnostic push
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_simple_buffer_Init(void);
void mock_simple_buffer_Destroy(void);
void mock_simple_buffer_Verify(void);




#define sb_construct_IgnoreAndReturn(cmock_retval) sb_construct_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sb_construct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return);
#define sb_construct_ExpectAndReturn(attr, sbd, cmock_retval) sb_construct_CMockExpectAndReturn(__LINE__, attr, sbd, cmock_retval)
void sb_construct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sb_attr_t* attr, sbd_t* sbd, sb_err_t cmock_to_return);
typedef sb_err_t (* CMOCK_sb_construct_CALLBACK)(sb_attr_t* attr, sbd_t* sbd, int cmock_num_calls);
void sb_construct_StubWithCallback(CMOCK_sb_construct_CALLBACK Callback);
#define sb_destruct_IgnoreAndReturn(cmock_retval) sb_destruct_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sb_destruct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return);
#define sb_destruct_ExpectAndReturn(sbd, cmock_retval) sb_destruct_CMockExpectAndReturn(__LINE__, sbd, cmock_retval)
void sb_destruct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t* sbd, sb_err_t cmock_to_return);
typedef sb_err_t (* CMOCK_sb_destruct_CALLBACK)(sbd_t* sbd, int cmock_num_calls);
void sb_destruct_StubWithCallback(CMOCK_sb_destruct_CALLBACK Callback);
#define sb_put_IgnoreAndReturn(cmock_retval) sb_put_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sb_put_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return);
#define sb_put_ExpectAndReturn(sbd, data, cmock_retval) sb_put_CMockExpectAndReturn(__LINE__, sbd, data, cmock_retval)
void sb_put_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t sbd, uint8_t data, sb_err_t cmock_to_return);
typedef sb_err_t (* CMOCK_sb_put_CALLBACK)(sbd_t sbd, uint8_t data, int cmock_num_calls);
void sb_put_StubWithCallback(CMOCK_sb_put_CALLBACK Callback);
#define sb_get_IgnoreAndReturn(cmock_retval) sb_get_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sb_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return);
#define sb_get_ExpectAndReturn(sbd, data, cmock_retval) sb_get_CMockExpectAndReturn(__LINE__, sbd, data, cmock_retval)
void sb_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t sbd, uint8_t* data, sb_err_t cmock_to_return);
typedef sb_err_t (* CMOCK_sb_get_CALLBACK)(sbd_t sbd, uint8_t* data, int cmock_num_calls);
void sb_get_StubWithCallback(CMOCK_sb_get_CALLBACK Callback);
#define sb_get_size_IgnoreAndReturn(cmock_retval) sb_get_size_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sb_get_size_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return);
#define sb_get_size_ExpectAndReturn(sbd, cmock_retval) sb_get_size_CMockExpectAndReturn(__LINE__, sbd, cmock_retval)
void sb_get_size_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t sbd, sb_err_t cmock_to_return);
typedef sb_err_t (* CMOCK_sb_get_size_CALLBACK)(sbd_t sbd, int cmock_num_calls);
void sb_get_size_StubWithCallback(CMOCK_sb_get_size_CALLBACK Callback);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#pragma GCC diagnostic pop
#endif

#endif
