/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "mock_simple_buffer.h"

static const char* CMockString_attr = "attr";
static const char* CMockString_data = "data";
static const char* CMockString_sb_construct = "sb_construct";
static const char* CMockString_sb_destruct = "sb_destruct";
static const char* CMockString_sb_get = "sb_get";
static const char* CMockString_sb_get_size = "sb_get_size";
static const char* CMockString_sb_put = "sb_put";
static const char* CMockString_sbd = "sbd";

typedef struct _CMOCK_sb_construct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  sb_err_t ReturnVal;
  int CallOrder;
  sb_attr_t* Expected_attr;
  sbd_t* Expected_sbd;

} CMOCK_sb_construct_CALL_INSTANCE;

typedef struct _CMOCK_sb_destruct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  sb_err_t ReturnVal;
  int CallOrder;
  sbd_t* Expected_sbd;

} CMOCK_sb_destruct_CALL_INSTANCE;

typedef struct _CMOCK_sb_put_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  sb_err_t ReturnVal;
  int CallOrder;
  sbd_t Expected_sbd;
  uint8_t Expected_data;

} CMOCK_sb_put_CALL_INSTANCE;

typedef struct _CMOCK_sb_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  sb_err_t ReturnVal;
  int CallOrder;
  sbd_t Expected_sbd;
  uint8_t* Expected_data;

} CMOCK_sb_get_CALL_INSTANCE;

typedef struct _CMOCK_sb_get_size_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  sb_err_t ReturnVal;
  int CallOrder;
  sbd_t Expected_sbd;

} CMOCK_sb_get_size_CALL_INSTANCE;

static struct mock_simple_bufferInstance
{
  int sb_construct_IgnoreBool;
  sb_err_t sb_construct_FinalReturn;
  CMOCK_sb_construct_CALLBACK sb_construct_CallbackFunctionPointer;
  int sb_construct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sb_construct_CallInstance;
  int sb_destruct_IgnoreBool;
  sb_err_t sb_destruct_FinalReturn;
  CMOCK_sb_destruct_CALLBACK sb_destruct_CallbackFunctionPointer;
  int sb_destruct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sb_destruct_CallInstance;
  int sb_put_IgnoreBool;
  sb_err_t sb_put_FinalReturn;
  CMOCK_sb_put_CALLBACK sb_put_CallbackFunctionPointer;
  int sb_put_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sb_put_CallInstance;
  int sb_get_IgnoreBool;
  sb_err_t sb_get_FinalReturn;
  CMOCK_sb_get_CALLBACK sb_get_CallbackFunctionPointer;
  int sb_get_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sb_get_CallInstance;
  int sb_get_size_IgnoreBool;
  sb_err_t sb_get_size_FinalReturn;
  CMOCK_sb_get_size_CALLBACK sb_get_size_CallbackFunctionPointer;
  int sb_get_size_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sb_get_size_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_simple_buffer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.sb_construct_IgnoreBool)
    Mock.sb_construct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sb_construct);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sb_construct_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sb_construct_CallbackFunctionPointer != NULL)
    Mock.sb_construct_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sb_destruct_IgnoreBool)
    Mock.sb_destruct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sb_destruct);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sb_destruct_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sb_destruct_CallbackFunctionPointer != NULL)
    Mock.sb_destruct_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sb_put_IgnoreBool)
    Mock.sb_put_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sb_put);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sb_put_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sb_put_CallbackFunctionPointer != NULL)
    Mock.sb_put_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sb_get_IgnoreBool)
    Mock.sb_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sb_get);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sb_get_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sb_get_CallbackFunctionPointer != NULL)
    Mock.sb_get_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sb_get_size_IgnoreBool)
    Mock.sb_get_size_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sb_get_size);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sb_get_size_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sb_get_size_CallbackFunctionPointer != NULL)
    Mock.sb_get_size_CallInstance = CMOCK_GUTS_NONE;
}

void mock_simple_buffer_Init(void)
{
  mock_simple_buffer_Destroy();
}

void mock_simple_buffer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.sb_construct_CallbackFunctionPointer = NULL;
  Mock.sb_construct_CallbackCalls = 0;
  Mock.sb_destruct_CallbackFunctionPointer = NULL;
  Mock.sb_destruct_CallbackCalls = 0;
  Mock.sb_put_CallbackFunctionPointer = NULL;
  Mock.sb_put_CallbackCalls = 0;
  Mock.sb_get_CallbackFunctionPointer = NULL;
  Mock.sb_get_CallbackCalls = 0;
  Mock.sb_get_size_CallbackFunctionPointer = NULL;
  Mock.sb_get_size_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

sb_err_t sb_construct(sb_attr_t* attr, sbd_t* sbd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sb_construct_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sb_construct);
  cmock_call_instance = (CMOCK_sb_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sb_construct_CallInstance);
  Mock.sb_construct_CallInstance = CMock_Guts_MemNext(Mock.sb_construct_CallInstance);
  if (Mock.sb_construct_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sb_construct_FinalReturn;
    memcpy(&Mock.sb_construct_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(sb_err_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sb_construct_CallbackFunctionPointer != NULL)
  {
    return Mock.sb_construct_CallbackFunctionPointer(attr, sbd, Mock.sb_construct_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_sb_construct,CMockString_attr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_attr), (void*)(attr), sizeof(sb_attr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_sb_construct,CMockString_sbd);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_sbd), (void*)(sbd), sizeof(sbd_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sb_construct(CMOCK_sb_construct_CALL_INSTANCE* cmock_call_instance, sb_attr_t* attr, sbd_t* sbd)
{
  cmock_call_instance->Expected_attr = attr;
  cmock_call_instance->Expected_sbd = sbd;
}

void sb_construct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_construct_CALL_INSTANCE));
  CMOCK_sb_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_construct_CallInstance = CMock_Guts_MemChain(Mock.sb_construct_CallInstance, cmock_guts_index);
  Mock.sb_construct_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sb_construct_IgnoreBool = (int)1;
}

void sb_construct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sb_attr_t* attr, sbd_t* sbd, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_construct_CALL_INSTANCE));
  CMOCK_sb_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_construct_CallInstance = CMock_Guts_MemChain(Mock.sb_construct_CallInstance, cmock_guts_index);
  Mock.sb_construct_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_sb_construct(cmock_call_instance, attr, sbd);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(sb_err_t));
  UNITY_CLR_DETAILS();
}

void sb_construct_StubWithCallback(CMOCK_sb_construct_CALLBACK Callback)
{
  Mock.sb_construct_IgnoreBool = (int)0;
  Mock.sb_construct_CallbackFunctionPointer = Callback;
}

sb_err_t sb_destruct(sbd_t* sbd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sb_destruct_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sb_destruct);
  cmock_call_instance = (CMOCK_sb_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sb_destruct_CallInstance);
  Mock.sb_destruct_CallInstance = CMock_Guts_MemNext(Mock.sb_destruct_CallInstance);
  if (Mock.sb_destruct_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sb_destruct_FinalReturn;
    memcpy(&Mock.sb_destruct_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(sb_err_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sb_destruct_CallbackFunctionPointer != NULL)
  {
    return Mock.sb_destruct_CallbackFunctionPointer(sbd, Mock.sb_destruct_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_sb_destruct,CMockString_sbd);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_sbd), (void*)(sbd), sizeof(sbd_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sb_destruct(CMOCK_sb_destruct_CALL_INSTANCE* cmock_call_instance, sbd_t* sbd)
{
  cmock_call_instance->Expected_sbd = sbd;
}

void sb_destruct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_destruct_CALL_INSTANCE));
  CMOCK_sb_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_destruct_CallInstance = CMock_Guts_MemChain(Mock.sb_destruct_CallInstance, cmock_guts_index);
  Mock.sb_destruct_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sb_destruct_IgnoreBool = (int)1;
}

void sb_destruct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t* sbd, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_destruct_CALL_INSTANCE));
  CMOCK_sb_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_destruct_CallInstance = CMock_Guts_MemChain(Mock.sb_destruct_CallInstance, cmock_guts_index);
  Mock.sb_destruct_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_sb_destruct(cmock_call_instance, sbd);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(sb_err_t));
  UNITY_CLR_DETAILS();
}

void sb_destruct_StubWithCallback(CMOCK_sb_destruct_CALLBACK Callback)
{
  Mock.sb_destruct_IgnoreBool = (int)0;
  Mock.sb_destruct_CallbackFunctionPointer = Callback;
}

sb_err_t sb_put(sbd_t sbd, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sb_put_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sb_put);
  cmock_call_instance = (CMOCK_sb_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sb_put_CallInstance);
  Mock.sb_put_CallInstance = CMock_Guts_MemNext(Mock.sb_put_CallInstance);
  if (Mock.sb_put_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sb_put_FinalReturn;
    memcpy(&Mock.sb_put_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(sb_err_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sb_put_CallbackFunctionPointer != NULL)
  {
    return Mock.sb_put_CallbackFunctionPointer(sbd, data, Mock.sb_put_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_sb_put,CMockString_sbd);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sbd), (void*)(&sbd), sizeof(sbd_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_sb_put,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sb_put(CMOCK_sb_put_CALL_INSTANCE* cmock_call_instance, sbd_t sbd, uint8_t data)
{
  memcpy(&cmock_call_instance->Expected_sbd, &sbd, sizeof(sbd_t));
  cmock_call_instance->Expected_data = data;
}

void sb_put_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_put_CALL_INSTANCE));
  CMOCK_sb_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_put_CallInstance = CMock_Guts_MemChain(Mock.sb_put_CallInstance, cmock_guts_index);
  Mock.sb_put_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sb_put_IgnoreBool = (int)1;
}

void sb_put_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t sbd, uint8_t data, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_put_CALL_INSTANCE));
  CMOCK_sb_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_put_CallInstance = CMock_Guts_MemChain(Mock.sb_put_CallInstance, cmock_guts_index);
  Mock.sb_put_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_sb_put(cmock_call_instance, sbd, data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(sb_err_t));
  UNITY_CLR_DETAILS();
}

void sb_put_StubWithCallback(CMOCK_sb_put_CALLBACK Callback)
{
  Mock.sb_put_IgnoreBool = (int)0;
  Mock.sb_put_CallbackFunctionPointer = Callback;
}

sb_err_t sb_get(sbd_t sbd, uint8_t* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sb_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sb_get);
  cmock_call_instance = (CMOCK_sb_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sb_get_CallInstance);
  Mock.sb_get_CallInstance = CMock_Guts_MemNext(Mock.sb_get_CallInstance);
  if (Mock.sb_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sb_get_FinalReturn;
    memcpy(&Mock.sb_get_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(sb_err_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sb_get_CallbackFunctionPointer != NULL)
  {
    return Mock.sb_get_CallbackFunctionPointer(sbd, data, Mock.sb_get_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_sb_get,CMockString_sbd);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sbd), (void*)(&sbd), sizeof(sbd_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_sb_get,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sb_get(CMOCK_sb_get_CALL_INSTANCE* cmock_call_instance, sbd_t sbd, uint8_t* data)
{
  memcpy(&cmock_call_instance->Expected_sbd, &sbd, sizeof(sbd_t));
  cmock_call_instance->Expected_data = data;
}

void sb_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_get_CALL_INSTANCE));
  CMOCK_sb_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_get_CallInstance = CMock_Guts_MemChain(Mock.sb_get_CallInstance, cmock_guts_index);
  Mock.sb_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sb_get_IgnoreBool = (int)1;
}

void sb_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t sbd, uint8_t* data, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_get_CALL_INSTANCE));
  CMOCK_sb_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_get_CallInstance = CMock_Guts_MemChain(Mock.sb_get_CallInstance, cmock_guts_index);
  Mock.sb_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_sb_get(cmock_call_instance, sbd, data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(sb_err_t));
  UNITY_CLR_DETAILS();
}

void sb_get_StubWithCallback(CMOCK_sb_get_CALLBACK Callback)
{
  Mock.sb_get_IgnoreBool = (int)0;
  Mock.sb_get_CallbackFunctionPointer = Callback;
}

sb_err_t sb_get_size(sbd_t sbd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sb_get_size_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sb_get_size);
  cmock_call_instance = (CMOCK_sb_get_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sb_get_size_CallInstance);
  Mock.sb_get_size_CallInstance = CMock_Guts_MemNext(Mock.sb_get_size_CallInstance);
  if (Mock.sb_get_size_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sb_get_size_FinalReturn;
    memcpy(&Mock.sb_get_size_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(sb_err_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sb_get_size_CallbackFunctionPointer != NULL)
  {
    return Mock.sb_get_size_CallbackFunctionPointer(sbd, Mock.sb_get_size_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_sb_get_size,CMockString_sbd);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sbd), (void*)(&sbd), sizeof(sbd_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sb_get_size(CMOCK_sb_get_size_CALL_INSTANCE* cmock_call_instance, sbd_t sbd)
{
  memcpy(&cmock_call_instance->Expected_sbd, &sbd, sizeof(sbd_t));
}

void sb_get_size_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_get_size_CALL_INSTANCE));
  CMOCK_sb_get_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_get_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_get_size_CallInstance = CMock_Guts_MemChain(Mock.sb_get_size_CallInstance, cmock_guts_index);
  Mock.sb_get_size_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sb_get_size_IgnoreBool = (int)1;
}

void sb_get_size_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sbd_t sbd, sb_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sb_get_size_CALL_INSTANCE));
  CMOCK_sb_get_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_sb_get_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sb_get_size_CallInstance = CMock_Guts_MemChain(Mock.sb_get_size_CallInstance, cmock_guts_index);
  Mock.sb_get_size_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_sb_get_size(cmock_call_instance, sbd);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(sb_err_t));
  UNITY_CLR_DETAILS();
}

void sb_get_size_StubWithCallback(CMOCK_sb_get_size_CALLBACK Callback)
{
  Mock.sb_get_size_IgnoreBool = (int)0;
  Mock.sb_get_size_CallbackFunctionPointer = Callback;
}

